# Generated by Django 5.0.1 on 2024-06-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_event_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
    ]
